name: Docker Build

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  
  
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-20.04
    if:      ${{ !contains(github.actor,'classroom' )}}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push 🤖
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKER_IMAGE}}:${{secrets.DOCKER_TAG}}
          cache-from: type=gha
          cache-to: type=gha,mode=max           
